### ISSUE TITLE
The docs regarding the install of the addon are not understandable.

### ISSUE THREAD

**Issue by Geams** [NitroxNova/Humanizer_Example#1]
_Important drag the global_config_override.res into the humanizer global scene and save, otherwise it will throw an error that it cant find the clothes_

Could you please explain what exactly you mean? 
There's no `global_config_override.res` so you probably mean `humanizer_global_config.tres` but how do I drag that 
into the scene `humanizer_global.tscn` there's no property to drag it onto.

**Comment by NitroxNova** [comment]
yes the humanizer_global_config.res. so you open the project settings>autoload and double click on the HumanizerGlobal, click the Config node and drag the override resource into there.  i understand its somewhat convoluted, had a guy helping me for several months and i am in the process of cleaning up his code and making it more usable

**Comment by NitroxNova** [comment]
oh actually i did go over the setup in the 1.0.1 update video (which is linked in the readme). https://www.youtube.com/watch?v=3NcCxrsrTmU its 6 minutes long, you really didnt watch it before commenting? around 4 minutes i literally show you how to do it. but i updated the readme as well, feel free to leave another issue if that didnt solve it
